environment:
  matrix:
  - nodejs_version: 4
  - nodejs_version: 6
  - nodejs_version: 7

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

test_script:
  - yarn run test

build: off
